[2020-06-01 20:17:33,184] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: test_dag_cvd.cvd 2020-05-30T00:15:00+00:00 [queued]>
[2020-06-01 20:17:33,191] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: test_dag_cvd.cvd 2020-05-30T00:15:00+00:00 [queued]>
[2020-06-01 20:17:33,191] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 20:17:33,191] {taskinstance.py:867} INFO - Starting attempt 1 of 3
[2020-06-01 20:17:33,191] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 20:17:33,206] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): cvd> on 2020-05-30T00:15:00+00:00
[2020-06-01 20:17:33,208] {standard_task_runner.py:53} INFO - Started process 14608 to run task
[2020-06-01 20:17:33,265] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: test_dag_cvd.cvd 2020-05-30T00:15:00+00:00 [running]> nineleaps
[2020-06-01 20:17:33,718] {taskinstance.py:1128} ERROR - 'newline' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/airflow_test.py", line 27, in cvd_api
    cvd = open('data_covid.csv', 'w', newline='\n')
TypeError: 'newline' is an invalid keyword argument for this function
[2020-06-01 20:17:33,722] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2020-06-01 20:17:43,179] {logging_mixin.py:112} INFO - [2020-06-01 20:17:43,178] {local_task_job.py:103} INFO - Task exited with return code 1
[2020-06-01 20:55:08,849] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: test_dag_cvd.cvd 2020-05-30T00:15:00+00:00 [queued]>
[2020-06-01 20:55:08,855] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: test_dag_cvd.cvd 2020-05-30T00:15:00+00:00 [queued]>
[2020-06-01 20:55:08,856] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 20:55:08,856] {taskinstance.py:867} INFO - Starting attempt 1 of 3
[2020-06-01 20:55:08,856] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-06-01 20:55:08,872] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): cvd> on 2020-05-30T00:15:00+00:00
[2020-06-01 20:55:08,876] {standard_task_runner.py:53} INFO - Started process 19259 to run task
[2020-06-01 20:55:08,938] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: test_dag_cvd.cvd 2020-05-30T00:15:00+00:00 [running]> nineleaps
[2020-06-01 20:55:09,623] {logging_mixin.py:112} INFO - csv loaded successfully.
[2020-06-01 20:55:09,623] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-01 20:55:09,626] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=test_dag_cvd, task_id=cvd, execution_date=20200530T001500, start_date=20200601T152508, end_date=20200601T152509
[2020-06-01 20:55:18,847] {logging_mixin.py:112} INFO - [2020-06-01 20:55:18,846] {local_task_job.py:103} INFO - Task exited with return code 0
